version: '3'

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    environment:
      - AWS_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - AWS_REGION=ap-northeast-1
      - AWS_LOG_ENDPOINT=http://localstack:4586
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4567-4586:4567-4586"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=logs
      - DEFAULT_REGION=ap-northeast-1
      - DEBUG=${DEBUG-1}
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=8080
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-docker}
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LANG=ja_JP.UTF-8
    volumes:
      - "./localstack:/tmp/localstack"
